---
apiVersion: v1
kind: Service
metadata:
  name: quarkus
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: quarkus

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: webanimo-angular
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - env:
            - name: animo.config.file.path
              value: /etc/animo/ANIMO_configuration.xml
            - name: quarkus.log.level
              value: DEBUG
          image: docker.io/marien99/webanimo-backend:1.0.1
          name: quarkus
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: docker.io/redis
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webanimo-angular
  name: webanimo-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webanimo-angular
  template:
    metadata:
      labels:
        app: webanimo-angular
    spec:
      containers:
        - image: docker.io/marien99/webanimo-v2:latest
          name: webanimo-angular
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always

