apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webanimo-angular
  name: webanimo-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webanimo-angular
  template:
    metadata:
      labels:
        app: webanimo-angular
    spec:
      containers:
        - image: "docker.io/marien99/webanimo-v2:{{ .Chart.AppVersion}}"
          name: webanimo-angular
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always

