services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  webanimo:
    image: uppaal-5.1.0
    ports:
      - '8080:8080'
    environment:
      - animo.config.file.path=/etc/animo/ANIMO_configuration.xml
