services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379'
  quarkus:
    image: marien99/webanimo-backend:1.0.30
    ports:
      - '8080:8080'
    environment:
      - animo.config.file.path=/etc/animo/ANIMO_configuration.xml
      - quarkus.log.level=DEBUG
  webanimo-angular:
    image: marien99/webanimo-v2:1.0.25
    ports:
      - '8081:8081'
